version: 2
updates:
  - commit-message:
      prefix: "Changelog:All"
    directory: /
    package-ecosystem: gitsubmodule
    schedule:
      interval: weekly
  - commit-message:
      prefix: 'Changelog:All'
    directory: /scripts/linkbot/
    package-ecosystem: npm
    schedule:
      interval: weekly
